seo: 
  site_name: 
  title: Default SEO Title 
  description: 
  keywords: 
  social_image: 
  author: 
  favicon_images: 
social: 
  instagram_username: 
  facebook_url: 
  twittwer_username: 
design: 
    yellow_color: '#FFBE00'
    navy_color: '#192B37'
